create table public.information_resources (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  organisation text not null,
  title text not null,
  description text not null,
  url text not null check (url ~ '^https://'),
  category text not null default 'GENERAL',
  language_code text not null default 'EN' check (language_code ~ '^[A-Z]{2,5}$'),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profile_information_resources (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  resource_id bigint not null references public.information_resources(id) on delete restrict,
  selected_at timestamptz not null default now(),
  primary key (profile_id, resource_id)
);

create index profile_information_resources_resource_id_idx
  on public.profile_information_resources(resource_id);

alter table public.information_resources enable row level security;
alter table public.profile_information_resources enable row level security;

grant select on public.information_resources to authenticated;
grant select, insert, delete on public.profile_information_resources to authenticated;
grant all on public.information_resources to service_role;
grant all on public.profile_information_resources to service_role;
grant usage, select on sequence public.information_resources_id_seq to service_role;

create policy "Members can view active information resources"
  on public.information_resources
  for select
  to authenticated
  using (active = true);

create policy "Members can view their own resource selections"
  on public.profile_information_resources
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = profile_information_resources.profile_id
        and p.user_id = (select auth.uid())
    )
  );

create policy "Members can add their own active resource selections"
  on public.profile_information_resources
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = profile_information_resources.profile_id
        and p.user_id = (select auth.uid())
    )
    and exists (
      select 1
      from public.information_resources r
      where r.id = profile_information_resources.resource_id
        and r.active = true
    )
    and (
      public.has_active_profile_health_consent(profile_information_resources.profile_id)
      or exists (
        select 1
        from public.profiles p
        where p.id = profile_information_resources.profile_id
          and p.is_demo = true
      )
    )
  );

create policy "Members can remove their own resource selections"
  on public.profile_information_resources
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = profile_information_resources.profile_id
        and p.user_id = (select auth.uid())
    )
  );

create or replace function public.enforce_profile_information_resource_limit()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if (
    select count(*)
    from public.profile_information_resources
    where profile_id = new.profile_id
  ) >= 3 then
    raise exception 'A profile can include no more than three information resources';
  end if;
  return new;
end;
$$;

revoke all on function public.enforce_profile_information_resource_limit() from public, anon, authenticated;

create trigger enforce_profile_information_resource_limit
before insert on public.profile_information_resources
for each row
execute function public.enforce_profile_information_resource_limit();

create or replace function public.set_profile_information_resources(
  p_profile_id uuid,
  p_resource_ids bigint[]
)
returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_resource_ids bigint[] := coalesce(p_resource_ids, '{}'::bigint[]);
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = p_profile_id
      and p.user_id = auth.uid()
  ) then
    raise exception 'Profile not found';
  end if;

  if cardinality(v_resource_ids) > 3 then
    raise exception 'Choose no more than three information resources';
  end if;

  if cardinality(v_resource_ids) <> (
    select count(distinct selected.resource_id)
    from unnest(v_resource_ids) as selected(resource_id)
  ) then
    raise exception 'Duplicate information resources are not allowed';
  end if;

  delete from public.profile_information_resources
  where profile_id = p_profile_id;

  insert into public.profile_information_resources(profile_id, resource_id)
  select p_profile_id, selected.resource_id
  from unnest(v_resource_ids) as selected(resource_id);
end;
$$;

revoke all on function public.set_profile_information_resources(uuid, bigint[]) from public, anon;
grant execute on function public.set_profile_information_resources(uuid, bigint[]) to authenticated;

insert into public.information_resources (
  slug,
  organisation,
  title,
  description,
  url,
  category,
  language_code,
  sort_order
)
values
  (
    'bls-what-is-lymphoedema',
    'British Lymphology Society',
    'What is lymphoedema?',
    'Specialist information about lymphoedema, the lymphatic system and available support.',
    'https://www.thebls.com/pages/what-is-lymphoedema',
    'UNDERSTANDING_LYMPHOEDEMA',
    'EN',
    10
  ),
  (
    'nhs-lymphoedema',
    'NHS',
    'Lymphoedema overview',
    'NHS information about symptoms, causes, diagnosis, treatment and possible complications.',
    'https://www.nhs.uk/conditions/lymphoedema/',
    'UNDERSTANDING_LYMPHOEDEMA',
    'EN',
    20
  ),
  (
    'bls-lsn-cellulitis-guidance',
    'British Lymphology Society and Lymphoedema Support Network',
    'Cellulitis guidance for lymphoedema',
    'Professional guidance about managing cellulitis in people living with lymphoedema.',
    'https://www.thebls.com/public/uploads/documents/document-91311757952788.pdf',
    'CELLULITIS',
    'EN',
    30
  )
on conflict (slug) do update
set organisation = excluded.organisation,
    title = excluded.title,
    description = excluded.description,
    url = excluded.url,
    category = excluded.category,
    language_code = excluded.language_code,
    active = true,
    sort_order = excluded.sort_order,
    updated_at = now();

create or replace function public.withdraw_profile_health_consent(
  p_profile_id uuid,
  p_version text,
  p_statement text
)
returns timestamptz
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_time timestamptz := now();
begin
  if v_user is null then
    raise exception 'Authentication required';
  end if;
  if not exists (
    select 1 from public.profiles
    where id = p_profile_id and user_id = v_user and is_demo = false
  ) then
    raise exception 'Profile not found';
  end if;

  insert into public.profile_privacy_events(profile_id,user_id,event_type,version,statement,created_at)
  values (p_profile_id,v_user,'HEALTH_CONSENT_WITHDRAWN',p_version,p_statement,v_time);

  update public.profiles
  set lymphoedema_type = null,
      lymphoedema_location = null,
      compression_information = null,
      treatment_considerations = null,
      assistance_needs = null,
      emergency_contact_name = null,
      emergency_contact_relationship = null,
      emergency_contact_phone = null,
      additional_statement = null,
      qr_profile_active = false,
      updated_at = v_time
  where id = p_profile_id and user_id = v_user;

  delete from public.profile_assistance where profile_id = p_profile_id;
  delete from public.profile_information_resources where profile_id = p_profile_id;

  update public.language_profiles
  set qr_profile_active = false,
      translated_content = '{}'::jsonb,
      translation_generated_at = null,
      translation_source_updated_at = null,
      translation_error = null,
      updated_at = v_time
  where source_profile_id = p_profile_id and user_id = v_user;

  return v_time;
end;
$$;
