create table if not exists public.admin_activity_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  actor_email text not null,
  action_type text not null,
  entity_type text,
  entity_id text,
  summary text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_activity_log enable row level security;

revoke all on table public.admin_activity_log from anon, authenticated;
grant select, insert on table public.admin_activity_log to service_role;
grant usage, select on sequence public.admin_activity_log_id_seq to service_role;

drop policy if exists admin_activity_log_service_role on public.admin_activity_log;
create policy admin_activity_log_service_role
on public.admin_activity_log
for all
to service_role
using (true)
with check (true);

create index if not exists admin_activity_log_created_at_idx
  on public.admin_activity_log (created_at desc);
create index if not exists admin_activity_log_action_type_idx
  on public.admin_activity_log (action_type, created_at desc);

insert into public.system_settings (setting_key, setting_value, updated_at)
values
  ('announcement_enabled','false',now()),
  ('announcement_message','',now()),
  ('announcement_start_at','',now()),
  ('announcement_end_at','',now()),
  ('feature_auto_renew_signup_enabled','true',now()),
  ('feature_additional_items_enabled','true',now()),
  ('feature_additional_languages_enabled','true',now()),
  ('communications_renewal_reminders_enabled','true',now()),
  ('communications_profile_review_reminders_enabled','true',now()),
  ('communications_expiry_notices_enabled','true',now()),
  ('communications_order_notifications_enabled','true',now()),
  ('communications_admin_notification_email','admin@lymphawareid.com',now())
on conflict (setting_key) do nothing;
