name: Diagnose registration check

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/diagnose-registration-check.yml'

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Call registration diagnostic
        shell: bash
        run: |
          set -x
          curl -i -sS 'https://lymphawareid.com/api/registration-diagnostic-240926'
